apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: spring-petclinic
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: spring-petclinic
  name: my-spring-petclinic
spec:
  replicas: '${ #toInt( parameters.replicas ) }'
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
          app: spring-petclinic
    spec:
      containers:
        - env:
            - name: db_script
              value: mysql
            - name: jdbc_driverClassName
              value: com.mysql.jdbc.Driver
            - name: jdbc_url
              value: 'jdbc:mysql://a956f7928021511eaae010ac87effead-830583172.us-east-1.elb.amazonaws.com:3306/petclinic?useUnicode=true'
            - name: jdbc_username
              value: root
            - name: jdbc_password
              value: mypassword
          image: '${ARTIFACT}'
          name: my-petclinic
          ports:
            - containerPort: 8080
      dnsPolicy: ClusterFirst
